/**
 * Shared report-deck renderer (HTML/CSS) used by BOTH the PDF and the standalone
 * HTML export (#12). Landscape, one slide per section, with structured metrics
 * grids + tables (#11). Callers pass ONLY client_visible items — the export gate
 * is enforced upstream (D8), so nothing internal can render here.
 */
import type { ReportContent } from "../../contract/types";

interface ReportLike {
  period: string;
  scope: { clients?: string[] } | any;
  exec_summary?: string | null;
}
interface ItemLike {
  section: string;
  content: ReportContent;
}

const esc = (s: string) =>
  String(s ?? "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

function metricsHtml(metrics?: ReportContent["metrics"]) {
  if (!metrics?.length) return "";
  return `<div class="metrics">${metrics
    .map(
      (m) =>
        `<div class="metric"><div class="m-val">${esc(m.value)}</div><div class="m-label">${esc(m.label)}</div>${m.sub ? `<div class="m-sub">${esc(m.sub)}</div>` : ""}</div>`,
    )
    .join("")}</div>`;
}

function tableHtml(table?: ReportContent["table"]) {
  if (!table?.rows?.length) return "";
  return `<table><thead><tr>${table.columns
    .map((c) => `<th>${esc(c)}</th>`)
    .join("")}</tr></thead><tbody>${table.rows
    .map((r) => `<tr>${r.map((c) => `<td>${esc(c)}</td>`).join("")}</tr>`)
    .join("")}</tbody></table>`;
}

export function buildReportHtml(report: ReportLike, items: ItemLike[]): string {
  const clients = (report.scope?.clients ?? []).join(", ") || "Client";
  const slides = items
    .map(
      (it) => `
      <section class="slide">
        <div class="eyebrow">${esc(it.section)}</div>
        <h2>${esc(it.content.title)}</h2>
        <p>${esc(it.content.body)}</p>
        ${metricsHtml(it.content.metrics)}
        ${tableHtml(it.content.table)}
      </section>`,
    )
    .join("");

  return `<!doctype html><html><head><meta charset="utf-8"/>
  <style>
    @page { size: A4 landscape; margin: 0; }
    * { box-sizing: border-box; }
    body { font-family: -apple-system, Segoe UI, Roboto, Helvetica, Arial, sans-serif; color: #1c2024; margin: 0; }
    .slide { min-height: 195mm; width: 100%; padding: 30px 44px; page-break-after: always; border-bottom: 1px solid #eee; }
    .cover { display: flex; flex-direction: column; justify-content: center; border-bottom: 4px solid #0f766e; }
    .brand { font-size: 13px; letter-spacing: .18em; text-transform: uppercase; color: #0f766e; font-weight: 700; }
    .cover h1 { font-size: 40px; margin: 12px 0 6px; }
    .cover .meta { color: #5b6670; font-size: 16px; }
    .badge { display:inline-block; margin-top:18px; padding:5px 12px; border:1px solid #0f766e33; border-radius:999px; color:#0f766e; font-size:12px; font-weight:700; width: fit-content; }
    .eyebrow { font-size: 11px; letter-spacing: .14em; text-transform: uppercase; color: #8b95a1; font-weight: 700; }
    .slide h2 { font-size: 26px; margin: 8px 0 10px; }
    .slide > p { font-size: 14px; line-height: 1.6; color: #36404a; margin: 0 0 18px; max-width: 80%; }
    .metrics { display: flex; flex-wrap: wrap; gap: 14px; margin: 8px 0 4px; }
    .metric { border: 1px solid #e6e8eb; border-radius: 12px; padding: 16px 20px; min-width: 150px; background: #fbfdfc; }
    .m-val { font-size: 30px; font-weight: 700; color: #0f766e; line-height: 1.1; }
    .m-label { font-size: 12px; color: #36404a; margin-top: 4px; font-weight: 600; }
    .m-sub { font-size: 11px; color: #8b95a1; margin-top: 2px; }
    table { border-collapse: collapse; width: 100%; margin-top: 6px; font-size: 13px; }
    th, td { text-align: left; padding: 9px 12px; border-bottom: 1px solid #e6e8eb; }
    th { font-size: 11px; text-transform: uppercase; letter-spacing: .06em; color: #5b6670; background: #f6f8f8; }
    .foot { padding: 14px 44px; color:#8b95a1; font-size: 11px; }
  </style></head>
  <body>
    <section class="slide cover">
      <div class="brand">Hitopia · Monthly Report</div>
      <h1>Performance — ${esc(report.period)}</h1>
      <div class="meta">${esc(clients)}</div>
      <div class="badge">Approved · client-safe</div>
    </section>
    ${slides}
    <div class="foot">Generated by Hitopia Monitoring. Decision-support only — figures trace to source metrics. Confidential.</div>
  </body></html>`;
}
